# Generated by Django 4.2 on 2024-08-17 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="order",
            name="order_order_createt_7ef041_idx",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="quantity",
            new_name="num",
        ),
    ]
